services:
  clickhouse:
    image: clickhouse
    hostname: clickhouse
    container_name: clickhouse
    restart: always
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    environment:
      CLICKHOUSE_USER: fabien
      CLICKHOUSE_PASSWORD: 
    networks:
      - syno_traefik
    volumes:
      - "/volume1/docker/clickhouse/data:/var/lib/clickhouse"
      - "/volume1/docker/clickhouse/logs:/var/log/clickhouse-server"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.clickhouse.entrypoints=tcp_clickhouse"
      - "traefik.tcp.routers.clickhouse.rule=HostSNI(`*`)"
      - "traefik.tcp.services.clickhouse.loadbalancer.server.port=8123"

networks:
  syno_traefik:
    external: true