version: "3"
services:

  # https://registry.hub.docker.com/_/postgres
  postgres-keycloak:
    image: library/postgres:13
    hostname: postgres-keycloak
    container_name: postgres-keycloak
    expose:
      - 15432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"


  # https://registry.hub.docker.com/r/jboss/keycloak
  keycloak:
    image: jboss/keycloak:15.0.2
    hostname: keycloak
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_PORT: 5432
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_DATABASE: keycloak
      # KEYCLOAK_LOGLEVEL: DEBUG
      # ROOT_LOGLEVEL: DEBUG
    volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - postgres-keycloak
