version: "3"
services:

  # https://registry.hub.docker.com/_/postgres
  postgres-keycloak:
    image: library/postgres:13
    hostname: postgres-keycloak
    container_name: postgres-keycloak
    expose:
      - 15432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak


  # https://registry.hub.docker.com/r/jboss/keycloak
  keycloak:
    image: jboss/keycloak:12.0.3
    hostname: keycloak
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_PORT: 5432
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_DATABASE: keycloak
    depends_on:
      - postgres-keycloak
