version: '3'
services:
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # - odfe-single:/usr/share/elasticsearch/data
      - ./config-elk/elasticsearch-config.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config-elk/elasticsearch-log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./config-elk/elasticsearch-security-config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
    ports:
      - 9200:9200

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
    hostname: kibana
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=https://host.docker.internal:9200
    volumes:
      - ./config-elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

#   logstash:
#     image: docker.elastic.co/logstash/logstash-oss:7.12.0
#     hostname: logstash
#     container_name: logstash
#     environment:
#       - ELASTICSEARCH_HOST=elasticsearch
#       - ELASTICSEARCH_PORT=9200
#     volumes:
#       - ./config-logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#       - ./config-logstash/custom-logstash.yml:/usr/share/logstash/config/logstash.yml
#     ports:
#      - 5000:5000
#      - 5000:5000/udp
#      - 5001:5001
#      - 12201:12201/udp # gelf for quarkus
#     depends_on:
#       - elasticsearch
