version: '3'
services:
  
  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    
  grafana:
    image: grafana/grafana:7.3.6
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000


