version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - 5432:5432
