Le_Domain='clickhouse.mend.ovh'
Le_Alt='no'
Le_Webroot='dns_ovh'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/2810157436/450067614436'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/2810157436/450067614436'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/059444d1f7546517100aac6fb9baca7b5550'
Le_CertCreateTime='1763499386'
Le_CertCreateTimeStr='2025-11-18T20:56:26Z'
Le_NextRenewTimeStr='2026-01-16T20:56:26Z'
Le_NextRenewTime='1768596986'
