AUTO_UPGRADE='1'
SAVED_OVH_AK='6c2f8d2e71b9afa6'
SAVED_OVH_AS='c017439ee2738c9877545ee100375cdd'
SAVED_OVH_CK='a52ceb9634841d67d4f2e4d87a049147'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
