version: '3.3'
services:
  nginx_rproxy: 
    image: nginx:latest
    container_name: nginx_rproxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/data/www  
    ports:
      - 80:80
    networks:
      - infranetwork


networks: 
  infranetwork:
    external: true
