version: "3"
services:

  # https://hub.docker.com/_/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - infra_network

  postgres:
    image: library/postgres:14
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - infra_network

  # https://hub.docker.com/r/dpage/pgadmin4/
  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin:
    image: dpage/pgadmin4:6
    hostname: pgadmin
    container_name: pgadmin
    # expose:
    #   - 80
    ports:
      - 8282:80
    environment:
      PGADMIN_DEFAULT_EMAIL: fabien@gmail.com
      PGADMIN_DEFAULT_PASSWORD: xxoca306
      SCRIPT_NAME: /pgadmin
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=PathPrefix(`/pgadmin`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - infra_network

networks:
  infra_network:
    external: true
