services:
  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    container_name: ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    hostname: openwebui
    container_name: openwebui
    restart: always
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data

volumes:
  ollama:
  open-webui:
