version: '3'
services:

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana:7.5.6
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config-grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config-grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./config-grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
#      - grafana-storage:/var/lib/grafana/

